version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:80"  # Map external port 8080 to container port 80
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
      - ./old-project:/usr/share/nginx/html  # Adjust the path to your old project